server:
  port: 8080
spring:
  cloud:
    compatibility-verifier:
      enabled: false
    discovery:
      client:
        simple:
          instances:
            verificationClient:
              - uri: http://localhost:8081
#  interface-clients:
#    http:
#      client-groups:
#        default:
#          base-url: http://localhost:9999
#        verificationClient:
#          base-url: http://localhost:8081
  application:
    name: http-verification-client
