server:
  port: 8080
spring:
  http:
    client:
      service:
        group:
          -verificationClient:
            base-url: http://localhost:8081
  application:
    name: http-verification-client


logging:
  level:
    org.springframework.boot: debug