server:
  port: 8080
spring:
#  http:
#    client:
#      service:
#        group:
#          -verificationClient:
#            base-url: http://verificationClient
  cloud:
#    loadbalancer:
#      clients:
#        -verificationClient:
#            interface-clients:
#              default-scheme: https
    #      interface-clients:
#        default-scheme: https
    compatibility-verifier:
      enabled: false
    discovery:
      client:
        simple:
          instances:
            verificationClient:
              - uri: http://localhost:8081
  application:
    name: http-verification-client
